# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
test="test"
script = "scripts"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./out" },
]

remappings = ["@solmate-utils/=lib/solmate/src/utils/"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
extra_output = ["devdoc", "storageLayout"]


[rpc_endpoints]
local = "http://0.0.0.0:8545"
dar = "https://ipc.dar.fluence.dev"
kras = "https://ipc.kras.fluence.dev"
stage = "https://rpc-123420000220.raas-testnet.gelato.digital"


